## Notebook11b

### Setup

Run all of the following before starting the notebook.

```{python}
#| tags: [noclear]
#| eval: false
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py
```

```{python}
#| tags: [noclear]
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())
pl.Config(tbl_rows=12)

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"
```

```{python}
#| tags: [remove]
#| include: false
ub = ""
```

```{python}
#| tags: [noclear]
weather = pl.read_csv(ub + "data/cities.csv")
```

## Linear Penalization 

Our data consists of the average temperature in world cities by month. To simplify the code, I've coded the months as mXX rather than their names. 

```{python}
weather
```

**One Month**
Throughout, we will try to predict the temperature of a city in June (month 6). Here is a linear regression of using just May (month 5) to do the prediction:

```{python}
(
    weather
    .pipe(
        DSSklearn.linear_regression,
        target=c.m06,
        features=[c.m05]
    )
    .coef()
)
```

**Two months**
Now, what happens if we use May and July? Think about this... Does it make sense that we would use a combination of the two in this way?

```{python}
(
    weather
    .pipe(
        DSSklearn.linear_regression,
        target=c.m06,
        features=[c.m05, c.m07]
    )
    .coef()
    .sort(c.name)
)
```

**Linear Regression (unpenalized)**
Now, let's use all of the months. But, rather than look at the values as a table, we will graph the data over the course of the year. 

```{python}
(
    weather
    .pipe(
        DSSklearn.linear_regression,
        target=c.m06,
        features=[c.m01, c.m02, c.m03, c.m04, c.m05, c.m07, c.m08, c.m09,
                  c.m10, c.m11, c.m12]
    )
    .coef()
    .filter(c.name != "Intercept")
    .sort(c.name)
    .pipe(ggplot, aes("name", "param"))
    + geom_point()
    + scale_x_discrete(limits=[f"m{x + 1:02d}" for x in range(12)])
    + geom_vline(xintercept="m06", color="red", linetype="dotted")
)
```

**Lasso**
Now, what happens if we use the cross-validated lasso regression. Notice what happens to the estimates. Does this make sense based on what you might think from the other models and the data?

```{python}
(
    weather
    .pipe(
        DSSklearn.elastic_net_cv,
        target=c.m06,
        features=[c.m01, c.m02, c.m03, c.m04, c.m05, c.m07, c.m08, c.m09,
                  c.m10, c.m11, c.m12],
                  l1_ratio=[1]
    )
    .coef()
    .filter(c.name != "Intercept")
    .sort(c.name)
    .pipe(ggplot, aes("name", "param"))
    + geom_point()
    + scale_x_discrete(limits=[f"m{x + 1:02d}" for x in range(12)])
    + geom_vline(xintercept="m06", color="red", linetype="dotted")
)
```

**Ridge Regression**
Here is the cross-validated (almost) ridge regression model.

```{python}
(
    weather
    .pipe(
        DSSklearn.elastic_net_cv,
        target=c.m06,
        features=[c.m01, c.m02, c.m03, c.m04, c.m05, c.m07, c.m08, c.m09,
                  c.m10, c.m11, c.m12],
                  l1_ratio=[0.001]
    )
    .coef()
    .filter(c.name != "Intercept")
    .sort(c.name)
    .pipe(ggplot, aes("name", "param"))
    + geom_point()
    + scale_x_discrete(limits=[f"m{x + 1:02d}" for x in range(12)])
    + geom_vline(xintercept="m06", color="red", linetype="dotted")
)
```

**Elastic Net**
And here is the elastic net model, with a ratio of 0.2.

```{python}
(
    weather
    .pipe(
        DSSklearn.elastic_net_cv,
        target=c.m06,
        features=[c.m01, c.m02, c.m03, c.m04, c.m05, c.m07, c.m08, c.m09,
                  c.m10, c.m11, c.m12],
                  l1_ratio=[0.2]
    )
    .coef()
    .filter(c.name != "Intercept")
    .sort(c.name)
    .pipe(ggplot, aes("name", "param"))
    + geom_point()
    + scale_x_discrete(limits=[f"m{x + 1:02d}" for x in range(12)])
    + geom_vline(xintercept="m06", color="red", linetype="dotted")
)
```

