## Notebook03a

### Setup

Run all of the following before starting the notebook.

```{python}
#| tags: [noclear]
#| eval: false
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py
```

```{python}
#| tags: [noclear]
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"
```

```{python}
#| tags: [remove]
#| include: false
ub = ""
```

```{python}
#| tags: [noclear]
food = pl.read_csv(ub + "data/food.csv").drop(c.description)
```

### Questions

We will continue working with the `food` dataset, this time focusing on visualizations using `plotnine`. Remember to look at your output after each question to understand what each piece of code does.

Create a scatter plot with vitamin A on the x-axis and iron on the y-axis.

```{python}
(
    food
    .pipe(ggplot, aes("vitamin_a", "iron"))
    + geom_point()
)
```

Now create a scatter plot with protein on the x-axis and fiber on the y-axis.

```{python}
(
    food
    .pipe(ggplot, aes("protein", "fiber"))
    + geom_point()
)
```

Let's add some data transformation before we plot the data. Recreate the previous plot, but only show the fruits.

```{python}
(
    food
    .filter(c.food_group == "fruit")
    .pipe(ggplot, aes("protein", "fiber"))
    + geom_point()
)
```

Finally (yes, this is a short notebook), let's aggregate the data before plotting it. Group by food group and count the number of rows in each group. Create a scatter plot that has the food group on the x-axis and the count on the y-axis. 

```{python}
(
    food
    .group_by(c.food_group)
    .agg(count = pl.len())
    .pipe(ggplot, aes("food_group", "count"))
    + geom_point()
)
```

Think about what changes you would like to make to this plot to make it more readable and interesting. We will get to (most) of those next time!
