## Notebook14a

### Setup

Run all of the following before starting the notebook.

```{python}
#| tags: [noclear]
#| eval: false
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py
```

```{python}
#| tags: [noclear]
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c

import torch.nn as nn
import torch.optim as optim

theme_set(theme_minimal())
pl.Config(tbl_rows=25)

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"
```

```{python}
#| tags: [remove]
#| include: false
ub = ""
```

```{python}
#| eval: false
#| tags: [noclear]
!wget -nc https://humanitiesdata.org/media/fashionmnist_10000.tar -P media/
!tar -xf media/fashionmnist_10000.tar -C media/
!wget -nc https://humanitiesdata.org/media/emnist_10000.tar -P media/
!tar -xf media/emnist_10000.tar -C media/
```

```{python}
#| tags: [noclear]
fmnist = pl.read_csv(ub + "data/fashionmnist_10000.csv")
emnist = pl.read_csv(ub + "data/emnist_10000.csv")
```

### Part I: Fashion MNIST

1. Use the code below to create the training and testing data. Notice this time that the shape of the data has changed. Make sure you understand what this means.

```{python}
#| tags: [noclear]
X, X_train, X_test, y, y_train, y_test, cn = DSTorch.load_image(
    fmnist, scale=True
)
X.shape
```

2. Next, use the following code to build a CNN model. Go through the parameters to understand the shape of the model. 

```{python}
#| tags: [noclear]
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.MaxPool2d(2),
          
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.net(x)
```

3. As before, we will use the Adam optimizer. After a little trial and error for the above parameters, I found a slightly higher learning rate (0.003) compared to last time was ideal.

```{python}
#| tags: [noclear]
model = SimpleCNN()
optimizer = optim.Adam(model.parameters(), lr=0.003)
```

4. Train the model. Notice that that the training loss will be worse because of the dropout, but it should help avoid overfitting. 

```{python}
#| tags: [noclear]
DSTorch.train(
    model, optimizer, X_train, y_train, num_epochs=20, batch_size=64
)
```

5. Look at the scores and confusion matrix of the training and testing sets. You will probably notice that the model does a bit better than the dense network, but the biggest improvement here is the dropout stopping the model from overfitting the training data.

```{python}
#| tags: [noclear]
DSTorch.score_image(model, X_train, y_train, cn)
```

```{python}
#| tags: [noclear]
DSTorch.score_image(model, X_test, y_test, cn)
```

```{python}
#| tags: [noclear]
DSTorch.confusion_matrix(model, X_test, y_test, cn)
```

6. Finally, let's look at the negative examples. How easily can *you* tell them apart?

```{python}
#| tags: [noclear]
(
    fmnist
    .with_columns(
        DSTorch.predict(model, X, y, cn)
    )
    .filter(c.target_ != c.prediction_)
    .with_columns(
        info = pl.concat_str(c.target_, c.prediction_, separator="=>")
    )
    .pipe(DSImage.plot_image_grid, label_name="info")
)
```

### Part II: EMNIST

7. Now look at the EMNIST dataset. We follow the same instructions as above, though the results themselves will be a bit different.

```{python}
#| tags: [noclear]
X, X_train, X_test, y, y_train, y_test, cn = DSTorch.load_image(
    emnist, scale=True
)
X.shape
```

8. Next, use the following code to build a CNN model. Go through the parameters to understand the shape of the model. 

```{python}
#| tags: [noclear]
class SimpleCNN(nn.Module):
    def __init__(self, num_classes=10):
        super().__init__()

        self.net = nn.Sequential(
            nn.Conv2d(1, 16, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.MaxPool2d(2),

            nn.Conv2d(16, 32, kernel_size=3, padding=1),
            nn.ReLU(),
            nn.Dropout(0.5),
            nn.MaxPool2d(2),
          
            nn.Flatten(),
            nn.Linear(32 * 7 * 7, 128),
            nn.ReLU(),
            nn.Linear(128, num_classes)
        )

    def forward(self, x):
        return self.net(x)
```

9. As before, we will use the Adam optimizer.

```{python}
#| tags: [noclear]
model = SimpleCNN(num_classes=len(cn))
optimizer = optim.Adam(model.parameters(), lr=0.003)
```

10. Train the model. Notice that that the training loss will be worse because of the dropout, but it should help avoid overfitting. 

```{python}
#| tags: [noclear]
DSTorch.train(
    model, optimizer, X_train, y_train, num_epochs=20, batch_size=64
)
```

11. Look at the scores of the training and testing sets. You will probably notice that the model does a bit better than the dense network, but the biggest improvement here is the dropout stopping the model from overfitting the training data.

```{python}
#| tags: [noclear]
DSTorch.score_image(model, X_train, y_train, cn)
```

```{python}
#| tags: [noclear]
DSTorch.score_image(model, X_test, y_test, cn)
```

12. Let's look at the negative examples. How easily can *you* tell them apart?

```{python}
#| tags: [noclear]
(
    emnist
    .with_columns(
        DSTorch.predict(model, X, y, cn)
    )
    .filter(c.target_ != c.prediction_)
    .sample(50)
    .with_columns(
        info = pl.concat_str(c.target_, c.prediction_, separator="=>")
    )
    .pipe(DSImage.plot_image_grid, label_name="info", ncol=5)
)
```

### Part III: EMNIST Metrics

Now for some coding on your own. We'll create a version of the emnist dataset with the predictions and then build some metrics for the data.

```{python}
emnist_pred = (
    emnist
    .with_columns(
        DSTorch.predict(model, X, y, cn)
    )
)
```


13.  The confusion matrix for this example is a bit too large to print (at least with the default settings in our code). Instead, in the block below, compute how often two pairs of labels are confused, as sort in descending order. You should see the most commonly confused pairs are quite reasonable.

```{python}
(
    emnist_pred
    .filter(c.target_ != c.prediction_)
    .group_by(c.target_, c.prediction_)
    .agg(count = pl.len())
    .sort(c.count, descending=True)
)
```

14. Now, create a dataset `df_recall` that has the recall of each class. Remember, this is, for each class, the proportion of items that were correctly predicted.

```{python}
df_recall = (
    emnist_pred
    .group_by(c.target_)
    .agg(recall = (c.target_ == c.prediction_).mean())
)
df_recall
```

15. Now, create a dataset `df_recall` that has the recall of each class. Remember, this is, for each class, the proportion of items that were predicted to be that class that were correct. You should notice that this is very similar to the code from the previous question.

```{python}
df_precision = (
    emnist_pred
    .group_by(c.prediction_)
    .agg(precision = (c.target_ == c.prediction_).mean())
)
df_precision
```

16. Join the precision and recall tables, compute the F1 scores, sort by the F1 scores, and print out all of the rows.

```{python}
(
    df_recall
    .join(df_precision, left_on="target_", right_on="prediction_")
    .with_columns(
        f1 = 2 * (c.precision * c.recall) / (c.precision + c.recall)
    )
    .sort(c.f1)
    .pipe(print_rows)
)
```
