## Notebook01a

This is our first Python notebook! The idea is just to have something to show (hopefully) how easy it is to get up and running in Python using Colab. Anyone can open this file and see the code. In order to run it, you'll need to be signed into a Google account.

### Setup

Every notebook will start with some setup code. Here, the first block downloads the class-specific helper functions, the second loads all of the Python modules we need, and the final one downloads the data that we are using in this notebook. We won't actually be using the data this time, but I've included it here just to demonstrate the normal process.

Run each of these cells in order by clicking on the triangular play button to the left when hoving on the cell. Wait for each to finish before continuing. 

```{python}
#| tags: [noclear]
#| eval: false
! wget -q -nc https://raw.githubusercontent.com/taylor-arnold/fds-py/refs/heads/main/funs.py
```

```{python}
#| tags: [noclear]
import numpy as np
import polars as pl

from funs import *
from plotnine import *
from polars import col as c
theme_set(theme_minimal())

ub = "https://raw.githubusercontent.com/taylor-arnold/fds-py-nb/refs/heads/main/"
```

```{python}
#| tags: [remove]
#| include: false
ub = ""
```

```{python}
#| tags: [noclear]
food = pl.read_csv(ub + "data/food.csv")
```

### Questions

Most notebooks will consist of blank blocks of code. There will be questions asking you to do certain things by writing code and then running it within each of the blocks. Sometimes, there will also be another question and corresponding **Answer**: tag after the code that asks you to provide a short textual response. You can type this directly after the tag. Let's try this out! In the block below, use Python to compute the sum of two plus two.

```{python}
2 + 2
```

What is the sum?
**Answer**: Four, of course!

As in the notes, create a variable called `my_fav_number` equal to your favorite number. Note: See those strange looking quotes around the variable name? Those are used to indicate that something in the prose text is a Python variable, function, or module. You will see that in the solutions these get printed in a code-font. Keep in mind that you do not copy the quotes themselves! 

```{python}
# the solutions often show possible answers rather than
# the only answer; also, there may be comments such as this
# that start with the # symbol and provide additional 
# feedback on the answer
my_fav_number = 8  
```

Now, use the function `np.log`, a function that comes from the numpy module to compute logarithms, to find the logarithm of 10.

```{python}
np.log(10)
```

If you are less mathematically-oriented, you might be worried that we are starting with a lot of mathematics? Don't be! This is only because it's the easiest thing to do before we have learned any of the data-specific functions that will come up in the next chapter. If you are very mathematically-oriented, you may be worried about by why the logarithm of 10 is not 1. The reason for this is the Python, like most programming languages but unlike most mathematical texts, uses the term log to indicate the natural logarithm (i.e., base e).

### Colab Setup

We have seen in the examples above that we can run Python code in Colab with no Colab-specific setup required. There are a few things that will be helpful to change in the default settings going forward. If you set these once from your Google account, they should persist without having the reset them each time. To start, click on Tools and Settings to open the settings box. Then:

- Under Editor change "Indentation width in spaces" to 4.
- Under Editor, unclick "Automatically close brackets..."
- Under Editor, under "Code Diagnostics" select "None"
- Under AI Assistance, click the "Hide generative AI features" and unclick everything else (very important!)

There are also two very important keyboard shortcuts to know:

- **Run selected cell in place**: Cmd + Enter (macOS), Ctrl + Enter (Windows) 
- **Run cell and move to next cell**: Shift + Enter (macOS and Windows)

A few other things are helpful to know about Colab. Under File, you can click on "Save a Copy in Drive". This will save your work in a special Colab folder within your Google Drive. Otherwise, you will loss all of your work when closing the window.

If you reopen the Notebook from your Google Drive, it will use your default language settings, which may be difficult to use if it is not in English. You can change this by selecting Help (always the last item in the menu) and "Show in English" (always the last item in the pull-down menu).

Finally, it seems that Google has been giving free Colab Pro accounts to students and educators. If you get a pop-up about this, it is worth going through the steps. While Colab is free, you'll get more powerful options for running code with the Pro version, which could be useful (but not necessary) in the later chapters.
